custom-level-name:
  1: Beginner
  2: Novice
  3: Intermediate
  4: Adept
  5: Advanced
  6: Expert
  7: Professional
  8: Master
  9: Ace
  10: Hero
  11: Lord
  12: Legend
  13: Infamous
  14: God
  15: Deity

  default: "Level {level}"